= Adding Reviewers 

Add one or more reviewers to a document action to verify and correct the documents queued for review due to low confidence score values or missing required fields. You can add single Anypoint Platform users or teams as reviewers. 

Add reviewers to a new document action while creating it or an existing document action by editing it. 

== Before You Begin 

Ensure you have any of the following Anypoint permissions:

include::partial$permissions.adoc[tag=permissionManage]

include::partial$permissions.adoc[tag=permissionBuild]

== Add Reviewers to a New Document Action

To create a new document action and add reviewers:

include::partial$create-document-actions.adoc[tag=initialSteps]

include::partial$add-reviewers.adoc[tag=commonSteps]

== Add Reviewers to an Existing Document Action

To edit an existing document action and add reviewers: 

. In the navigation panel, click *Document Actions*.
. Click a document action to open its view page.

include::partial$add-reviewers.adoc[tag=commonSteps]

== See Also 

* xref:publishing-document-actions.adoc[]
* xref:creating-document-actions.adoc[]
* xref:reviewing-processed-documents.adoc[]