= Analyzing Documents and Customizing the Output With Einstein

Analyze any type of document and fully customize the output structure by using the Generic document action with Einstein. You can define fiel, table, and column names and configure instructions for Einstein to analyze the document and extract the data.   

include::partial$einstein-model.adoc[tag=einsteinGeneric]

include::partial$document-action.adoc[tag=definition] 

After you create a document action, add reviewers and publish it to Anypoint Exchange. Publishing the document action enables RPA to execute it and also creates an API that you can call from any external system to analyze your documents. 

For instructions about using Einstein in your document actions that use pre-built schemas, see xref:creating-document-actions.adoc[]

== Before You Begin Using Einstein

. Ensure you have any of the following Anypoint permissions:
+
include::partial$permissions.adoc[tag=permissionManage]
+
include::partial$permissions.adoc[tag=permissionBuild]

include::partial$einstein.adoc[tags=einsteinRequisites;!shortIntro]

== Create a Generic Document Action and Enable Einstein

To analyze documents with Einstein, create a document action of the Generic type and Enable Einstein:

. In the sidebar, click *Document Actions*.
. Click *Create New*.
. Select the *Generic* type. 
. Enable *Use Einstein*. 
. Provide a Name and click *Create*.

Next, add the Fields and Tables to extract. 

== Add the Fields to Extract

To configure the fields to extract and define the structure of the output document:

. In the document action builder, click *Select Files* and select the files to use as an example or model for the extraction. 
. In the *Outputs* panel, select the *Fields* tab. 
. Click *Start from Scratch* to add the first field. 
. Provide a name for the field and a prompt.
+
If you don't configure a prompt, Einstein scans the document and automatically extracts the data that better suits the field. However, make sure you test the output to confirm the extracted field matches the expected result. Otherwise, configure a prompt to provide Einstein with specific instructions about how to populate that field. 
. Click *Add New* to continue adding fields.
. Click *Run* and verify the results of the extraction. 
. Click *Save*.

== Add the Tables to Extract

To configure data extraction from tables:

. In the document action builder, click *Select Files* and select the files to use as an example or model for the extraction.
+
Skip this step if the example file is already loaded. 
. In the *Outputs* panel, select the *Tables* tab. 
. Click *Start from Scratch* to add the first table. 
. Provide a name for the table and a prompt if necessary to configure the data to extract.
. Click *Add New Column* and provide a name and prompt for the column. 
** Continue adding columns until the table is complete. 
. If there are more tables to configure, click *Add New* and repeat the steps to add the table columns.
. Click *Run* and verify the results of the extraction. 
. Click *Save*.

After you finish configuring the output schema for your documents, add reviewers and publish your document action. 

== Configure Document Action Settings

When you create a Generic document action with Einstein, you can configure these settings: 

* *Model*
+
Select the predictive model to use when executing this document action. 
* *Enable PII Masking*
+
Mask any personally identifiable information from your documents before sending it to the predictive model. Your Salesforce Organization Preferences override this setting. For more information, see https://help.salesforce.com/s/articleView?id=ai.generative_ai_trust_layer.htm&type=5[Einstein Trust Layer].


== See Also 

* xref:adding-reviewers.adoc[]
* xref:publishing-document-actions.adoc[]
* xref:creating-document-actions.adoc[]
* xref:rpa-home::index.adoc[]