= Automating Document Processing

IDP enables you to automate the data extraction process by integrating your document actions with Mule applications and other systems. 

After you create and publish document actions to Anypoint Exchange, they become available as APIs that you can call programmatically by configuring a Connected App and its corresponding access token.  

== Before You Begin

Before you begin integrating IDP with other applications, ensure that: 

* You created one or more document actions. 
* The document actions are published. 

== Integrating Document Actions With Your Application

To start integrating IDP with other applications:

. <<create-connected-app>>
. <<obtain-access-token>>
. <<call-document-actions>>

[[create-connected-app]]
== Create a Connected App

To communicate with the document action API, create a Connected App with the following details: 

* Type: `App acts on its own behalf (client credentials)`
* Scopes: `Execute Document Actions`

After you create the Connected App, copy its *ID* and *Secret* for further use when obtaining the access token. 

For more instructions about creating a Connected App, see xref::access-management::connected-apps-developers.adoc#create-a-connected-app[].

[[obtain-access-token]]
== Obtain the Access Token

After you configure the Connected App, use the following `curl` command to get the token: 

[source,bash,linenums]
----
curl --location --request POST 'https://anypoint.mulesoft.com/accounts/api/v2/oauth2/token' \ // <1>
--header 'Content-Type: application/json' \
--data-raw '{
 "grant_type": "client_credentials",
 "client_id": "<connected-app-client-id>", // <2>
 "client_secret": "<connected-app-client-secret>" // <3> 
}'
----
[calloutlist]
.. If you are in the EU region, add the `eu1.` subdomain to `anypoint.mulesoft.com`.
.. Replace `<connected-app-client-id>` with the client ID from your Connected App.
.. Replace `<connected-app-client-secret>` with the client Secret from your Connected App.

Use the access token when calling the document action API.

[[call-document-actions]]
== Use the Published Document Actions  

After you've published document actions, configured a connected app, and obtained the access token, you can start calling the document actions to trigger their execution.

Because the API's documentation is part of the specification, you can see the documentation in the API portal after you publish the document actions to Exchange. 

== See Also 

* xref:creating-document-actions.adoc[]
* xref:publishing-document-actions.adoc[]