= Processing Documents and Retrieving Results With the API
:keywords: idp api, intelligent document processing, document actions, callback url, supported regions, automate document processing

You can automate the data extraction process by using the IDP API to integrate your document actions with Mule applications and other systems. Integrating with IDP requires creating a connected app, obtaining the access token, and calling the IDP API to execute document actions and retrieve the results.

Use the IDP API to execute your published actions and retrieve the results of the execution. You can also specify an HTTPS callback URL for IDP to call when the process finishes. 

Instead of calling the IDP API to execute your document actions, you can use the Submit Document to MuleSoft IDP and Retrieve Results from MuleSoft IDP action steps from MuleSoft RPA. For instructions on integrating your document actions with MuleSoft RPA, see xref:automate-document-processing-with-rpa.adoc[].

== Before You Begin 

Ensure you have the following Anypoint permissions:

include::partial$permissions.adoc[tag=permissionExecute]

//include::partial$permissions.adoc[tag=permissionConfigure]

include::partial$connected-app-config.adoc[tag=createConnectedApp]

include::partial$connected-app-config.adoc[tag=obtainAccessToken]

== Execute the Published Document Actions

After you publish document actions, configure a connected app, and obtain the access token, you can call the IDP API to execute your document actions.

[[supported-regions]]
=== Supported Regions

IDP is available in these regions:

[%header%autowidth.spread,cols=".^a,.^a"]
|===
| Region | Base URL

| US East (Virginia)
| `\https://idp-rt.us-east-1.anypoint.mulesoft.com`

| EU Central (Frankfurt)
| `\https://idp-rt.eu-central-1.eu1.anypoint.mulesoft.com`
|===

Use the appropriate base URL for your region when calling the IDP API.

The following is a sample call that provides guidance about how to construct an API call to execute a document action:

[source,bash,linenums]
----
curl --location 'https://idp-rt.{region}.anypoint.mulesoft.com/api/v1/organizations/{orgId}/actions/{actionId}/versions/{actionVersion}/executions' \
--header 'Authorization: Bearer {token}' \
--form 'file=@"{pathToFile}"'
----

Replace `{region}` with either `us-east-1` or `eu-central-1.eu1` depending on your region.

include::partial$document-action.adoc[tag=modelUsage]

[[callback-url]]
=== Define a Callback URL

You can define a callback URL when you call IDP to execute your document actions. If defined, IDP calls the callback URL when the document action execution finishes with state `SUCCEEDED`, `FAILED`, or `MANUAL_VALIDATION_REQUIRED`. The callback URL must use HTTPS.

To specify the callback URL, include the `callback` field in your API call and define a JSON value with the callback URL. The following example adds a callback to the previous `curl` command example:

[source,bash,linenums]
----
curl --location 'https://idp-rt.{region}.anypoint.mulesoft.com/api/v1/organizations/{orgId}/actions/{actionId}/versions/{actionVersion}/executions' \
--header 'Authorization: Bearer {token}' \
--form 'file=@"{pathToFile}"' \
--form 'callback="{\"noAuthUrl\":\"{callbackURL}\"}"'
----

[[upload-base64-file]]
=== Upload a Base64-Encoded File 

You can upload a Base64-encoded file when you call the IDP API to execute your versioned document actions. For example: 

[source,bash,linenums]
----
curl --location 'https://idp-rt.{region}.anypoint.mulesoft.com/api/v1/organizations/{orgId}/actions/{actionId}/versions/{actionVersion}/executions' \
--header 'Content-Type: application/json' \
--header 'Authorization: Bearer {token}' \
--data '{
    "file": {yourBase64string},
    "fileName": {testFileName.pdf}
    }'
----

=== Use a Different Salesforce Org to Execute Your Document Actions

If you have multiple Salesforce Orgs connected with your Anypoint Platform organization, you can specify the Org to use when executing your document actions.

To specify a Salesforce Org, add the following header to the API call: 

* `x-sfdc-core-tenant-id=<18-char-sfdc-org-id>`
+
Replace `<18-char-sfdc-org-id>` with your Salesforce Org ID.

== Retrieve the Results of the Execution

After a document action successfully processes a document, or after a reviewer verifies and submits a document queued for review, the results are available for consumption.

When you use the IDP API to execute your document actions, retrieve the results by calling the `/executions` endpoint and providing an `executionId`, for example:

[source,bash,linenums]
----
curl --location \
'https://idp-rt.{{region}}.anypoint.mulesoft.com/api/v1/organizations/{orgId}/actions/{actionId}/versions/{actionVersion}/executions/{executionId}/v2' \
--header 'Authorization: Bearer {token}'
----

[[include-confidence-scores]]
=== Include Confidence Scores and Metadata in Results

By default, the API returns only the extracted field values. To retrieve additional metadata such as confidence scores, field geometry (position and dimensions), and page numbers, add the `valueOnly=false` query parameter to your GET request:

[source,bash,linenums]
----
curl --location \
'https://idp-rt.{{region}}.anypoint.mulesoft.com/api/v1/organizations/{orgId}/actions/{actionId}/versions/{actionVersion}/executions/{executionId}?valueOnly=false' \
--header 'Authorization: Bearer {token}'
----

When you set `valueOnly=false`, the response includes the following additional information for each extracted field and table item:

* `confidenceScore`: Confidence level of the extracted value (0-100)
* `geometry`: Position and dimensions of the field on the page
+
--
** `width`: Width of the field as a percentage of page width
** `height`: Height of the field as a percentage of page height
** `left`: Distance from the left edge as a percentage of page width
** `top`: Distance from the top edge as a percentage of page height
--
+
[NOTE]
If *Location callouts* is disabled, `geometry` shows `null`.
+
* `pageNumber`: Page number where the field was found

This example is a fragment of a response that shows the additional information.
[source,json]
----
...
"fields": {
  "shipVia": null,
  "fob": null,
  "carrier": null,
  "tax": {
    "value": "71.05",
    "confidenceScore": 99.9162,
    "geometry": {
      "width": 0.044640772,
      "height": 0.011198458,
      "left": 0.88380444,
      "top": 0.49255127
    }
  },
  "purchaseOrderDate": {
    "value": "06/28/2024",
    "confidenceScore": 99.906105,
    "geometry": {
      "width": 0.08811343,
      "height": 0.011008841,
      "left": 0.8385502,
      "top": 0.20239446
    }
  },
...
----

[NOTE] 
The `valueOnly` parameter is available when calling the IDP API directly using HTTP requests. This parameter is not supported when using the IDP connector in Anypoint Studio.

[[execution-status-reference]]
== Execution Results Reference 

When you query the results of an execution, the IDP API returns any of the following statuses: 

* `ACKNOWLEDGED`: The document action execution request was received.
* `IN_PROGRESS`: The execution started.
* `RESULTS_PENDING`: The execution finished and IDP is processing the results.
* `MANUAL_VALIDATION_REQUIRED`: The execution finished but the results need manual validation.
* `FAILED`: The execution request finished unsuccessfully.
* `PARTIAL_SUCCESS`: The execution request finished but some sub-tasks failed.
* `SUCCEEDED`: The execution request finished successfully. 

== IDP API Documentation 

To confirm the endpoints to call to trigger document action executions and retrieve results, refer to the API documentation. The IDP API documentation is part of the specification and shows in the API portal after you publish the document actions to Anypoint Exchange. 

== See Also 

* xref:rpa-builder::toolbox-mulesoft-idp-submit-document-to-mulesoft-idp.adoc[]
* xref:rpa-builder::toolbox-mulesoft-idp-retrieve-results-from-mulesoft-idp.adoc[]
* xref:creating-document-actions.adoc[]
* xref:publishing-document-actions.adoc[]
