= Processing Documents and Retrieving Results With the API

You can automate the data extraction process by using the IDP API to integrate your document actions with Mule applications and other systems. Integrating with IDP requires creating a connected app, obtaining the access token, and calling the IDP API to execute document actions and retrieve the results.

Use the IDP API to execute your published actions and retrieve the results of the execution. You can also specify a callback URL for IDP to call when the process finishes. 

Instead of calling the IDP API to execute your document actions, you can use the Submit Document to MuleSoft IDP and Retrieve Results from MuleSoft IDP action steps from MuleSoft RPA. For instructions on integrating your document actions with MuleSoft RPA, see xref:automate-document-processing-with-rpa.adoc[].

== Before You Begin 

Ensure you have the following Anypoint permissions:

include::partial$permissions.adoc[tag=permissionExecute]

include::partial$permissions.adoc[tag=permissionConfigure]

include::partial$connected-app-config.adoc[tag=createConnectedApp]

include::partial$connected-app-config.adoc[tag=obtainAccessToken]

== Execute the Published Document Actions  

After you publish document actions, configure a connected app, and obtain the access token, you can call the IDP API to execute your document actions.

The following is a sample call that provides guidance about how to construct an API call to execute a document action:

[source,bash,linenums]
----
curl --location 'https://idp-rt.{region}.anypoint.mulesoft.com/api/v1/organizations/{orgId}/actions/{actionId}/versions/{actionVersion}/executions' \
--header 'Authorization: Bearer {token}' \
--form 'file=@"{pathToFile}"'
----

=== Define a Callback URL

You can define a callback URL when you call IDP to execute your document actions. If defined, IDP calls the callback URL when the document action execution finishes. 

To specify the callback URL, include the `callback` field in your API call and define a JSON value with the callback URL. The following example adds a callback to the previous `curl` command example:

[source,bash,linenums]
----
curl --location 'https://idp-rt.{region}.anypoint.mulesoft.com/api/v1/organizations/{orgId}/actions/{actionId}/versions/{actionVersion}/executions' \
--header 'Authorization: Bearer {token}' \
--form 'file=@"{pathToFile}"' \
--form 'callback="{\"noAuthUrl\":\"{callbackURL}\"}"'
----

== Retrieve the Results of the Execution

After a document action successfully processes a document, or after a reviewer verifies and submits a document queued for review, the results are available for consumption. 

When you use the IDP API to execute your document actions, retrieve the results by calling the `/executions` endpoint and providing an `executionId`, for example: 

[source,bash,linenums]
----
curl --location \
'https://idp-rt.{{region}}.anypoint.mulesoft.com/api/v1/organizations/{orgId}/actions/{actionId}/versions/{actionVersion}/executions/{executionId}/v2' \
--header 'Authorization: Bearer {token}'
----

[[execution-status-reference]]
== Execution Results Reference 

When you query the results of an execution, the IDP API returns any of the following statuses: 

* `ACKNOWLEDGED`: The document action execution request was received.
* `IN_PROGRESS`: The execution started.
* `RESULTS_PENDING`: The execution finished and IDP is processing the results.
* `MANUAL_VALIDATION_REQUIRED`: The execution finished but the results need manual validation.
* `FAILED`: The execution request finished unsuccessfully.
* `PARTIAL_SUCCESS`: The execution request finished but some sub-tasks failed.
* `SUCCEEDED`: The execution request finished successfully. 

== IDP API Documentation 

To confirm the endpoints to call to trigger document action executions and retrieve results, refer to the API documentation. The IDP API documentation is part of the specification and shows in the API portal after you publish the document actions to Anypoint Exchange. 

== See Also 

* xref:rpa-builder::toolbox-mulesoft-idp-submit-document-to-mulesoft-idp.adoc[]
* xref:rpa-builder::toolbox-mulesoft-idp-retrieve-results-from-mulesoft-idp.adoc[]
* xref:creating-document-actions.adoc[]
* xref:publishing-document-actions.adoc[]