= Process Documents and Retrieve Results With the API

IDP provides an API that enables you to automate the data extraction process by integrating your document actions with Mule applications and other systems. Integrating with IDP requires creating a Connected App, obtaining the access token, and calling the IDP API to execute document actions and retrieve the results.

Because RPA integrates seamlessly with IDP, you don't need to configure a Connected App and call the API to execute document actions. After you publish a document action, RPA can interact with it by using the Send Document and Retrieve Results action steps.

For instructions to execute document actions from RPA, see xref:automate-document-processing-with-rpa.adoc[].

== Create a Connected App

To communicate with the IDP API, create a Connected App with the following details: 

* Type: `App acts on its own behalf (client credentials)`
* Scopes: `Execute Versioned Actions`

After you create the Connected App, copy its *ID* and *Secret* for further use when obtaining the access token. 

For more instructions about creating a Connected App, see xref::access-management::connected-apps-developers.adoc#create-a-connected-app[].

== Obtain the Access Token

After you configure the Connected App, use the following `curl` command to get the token: 

[source,bash,linenums]
----
curl --location --request POST 'https://anypoint.mulesoft.com/accounts/api/v2/oauth2/token' \ // <1>
--header 'Content-Type: application/json' \
--data-raw '{
 "grant_type": "client_credentials",
 "client_id": "<connected-app-client-id>", // <2>
 "client_secret": "<connected-app-client-secret>" // <3> 
}'
----
[calloutlist]
.. If you are in the EU region, add the `eu1.` subdomain to `anypoint.mulesoft.com`.
.. Replace `<connected-app-client-id>` with the client ID from your Connected App.
.. Replace `<connected-app-client-secret>` with the client Secret from your Connected App.

Use the access token when calling the document action API.

== Execute the Published Document Actions  

After you publish document actions, configure a connected app, and obtain the access token, you can start calling the IDP API to execute your document actions.

The following is a sample call that provide guidance about how to construct an API call to execute a document action:

[source,bash,linenums]
----
curl -H 'Authorization: Bearer {token}' -X POST -H 'Content-Type: multipart/form-data' \ 
'https://idp-rt.{{region}}.anypoint.mulesoft.com/api/v1/organizations/{orgId}/actions/{actionId}/versions/{actionVersion}/executions/v2' \ 
--form file="@file.pdf"
----

== Retrieve the Results 

After a document action successfully processes a document, or after a reviewer verifies and submits a document queued for review, the results are available for consumption. 

When you use the IDP API to execute your document actions, retrieve the results by calling the `/executions` endpoint of the IDP API and providing an `executionId`. For example: 

[source,bash,linenums]
----
curl --location \
'https://idp-rt.{{region}}.anypoint.mulesoft.com/api/v1/organizations/{orgId}/actions/{actionId}/versions/{actionVersion}/executions/{executionId}/v2' \
--header 'Authorization: Bearer {token}'
----

[[execution-status-reference]]
== Execution Results Reference 

When you query the results of an execution, the IDP API returns any of the following statuses: 

* *ACKNOWLEDGED*: The document action execution request was received.
* *IN_PROGRESS*: The execution started.
* *RESULTS_PENDING*: The execution finished and is processing the results.
* *MANUAL_VALIDATION_REQUIRED*: The execution finished but the results need manual validation.
* *FAILED*: The execution request finished unsuccessfully.
* *PARTIAL_SUCCESS*: The execution request finished but some sub-tasks failed.
* *SUCCEEDED*: The execution request has finished successfully. 

== IDP API Documentation 

The IDP API documentation is part of the specification and shows in the API portal after you publish the document actions to Anypoint Exchange. Refer to the API documentation to confirm the endpoints you must call to trigger document action executions and retrieve results. 

== See Also 

// RPA: Send Document action step
// RPA: Retrieve Results action step
* xref:creating-document-actions.adoc[]
* xref:publishing-document-actions.adoc[]