= Automate Document Processing With the IDP API

IDP provides an API that enables you to automate the data extraction process by integrating your document actions with RPA processes, Mule applications, and other systems. 

IDP integrates seamlessly with RPA by using the Send Document and Retrieve Results action steps from your automated processes. After you publish a document action, RPA can interact with it by using the mentioned action steps. 

Integrating IDP with other applications requires creating a Connected App, obtaining the access token, and calling the IDP API.

== Before You Begin Your Integration

Before you begin integrating IDP with other applications, ensure that: 

* You created one or more document actions. 
* The document actions are published. 

[[create-connected-app]]
== Create a Connected App

To communicate with the IDP API, create a Connected App with the following details: 

* Type: `App acts on its own behalf (client credentials)`
* Scopes: `Execute Document Actions`

After you create the Connected App, copy its *ID* and *Secret* for further use when obtaining the access token. 

For more instructions about creating a Connected App, see xref::access-management::connected-apps-developers.adoc#create-a-connected-app[].

[[obtain-access-token]]
== Obtain the Access Token

After you configure the Connected App, use the following `curl` command to get the token: 

[source,bash,linenums]
----
curl --location --request POST 'https://anypoint.mulesoft.com/accounts/api/v2/oauth2/token' \ // <1>
--header 'Content-Type: application/json' \
--data-raw '{
 "grant_type": "client_credentials",
 "client_id": "<connected-app-client-id>", // <2>
 "client_secret": "<connected-app-client-secret>" // <3> 
}'
----
[calloutlist]
.. If you are in the EU region, add the `eu1.` subdomain to `anypoint.mulesoft.com`.
.. Replace `<connected-app-client-id>` with the client ID from your Connected App.
.. Replace `<connected-app-client-secret>` with the client Secret from your Connected App.

Use the access token when calling the document action API.

[[call-document-actions]]
== Execute the Published Document Actions  

After you publish document actions, configure a connected app, and obtain the access token, you can start calling the IDP API to execute your document actions.

Following are some sample calls that provide guidance about how to construct an API call to IDP:

.Execute a document action 
[source,bash,linenums]
----
curl -H 'Authorization: Bearer {token}' -X POST -H 'Content-Type: multipart/form-data' \ 
'https://idp-rt.us-east-1.anypoint.mulesoft.com/api/v1/organizations/{orgId}/actions/{actionId}/versions/{actionVersion}/executions/v2' \ 
--form file="@file.pdf"
----

.Retrieve results 
[source,bash,linenums]
----
curl --location \
'https://idp-rt.us-east-1.anypoint.mulesoft.com/api/v1/organizations/{orgId}/actions/{actionId}/versions/{actionVersion}/executions/{executionId}/v2' \
--header 'Authorization: Bearer {token}'
----

=== IDP API Documentation 

The IDP API documentation is part of the specification and shows in the API portal after you publish the document actions to Anypoint Exchange. Refer to the API documentation to confirm the endpoints you must call to trigger document action executions and retrieve results. 

== See Also 

// RPA: Send Document action step
// RPA: Retrieve Results action step
* xref:creating-document-actions.adoc[]
* xref:publishing-document-actions.adoc[]