= Processing Documents and Retrieving Results With RPA

You can execute your published document actions with MuleSoft RPA by using the Submit Document to MuleSoft IDP and Retrieve Results from MuleSoft IDP action steps in your automation projects. 
After you publish a document action to Anypoint Exchange, it becomes available for consumption in RPA. You must create a connected app and obtain the access token before you can use the IDP action steps in RPA. 

If you aren't using RPA to execute your document actions, configure and call the IDP API, as described in xref:automate-document-processing-with-the-idp-api.adoc[].

== Before You Begin 

Ensure you have the following Anypoint permissions:

include::partial$permissions.adoc[tag=permissionExecute]

//include::partial$permissions.adoc[tag=permissionConfigure]

// Connected App section
include::partial$connected-app-config.adoc[tag=createConnectedApp]

// Access Token section
include::partial$connected-app-config.adoc[tag=obtainAccessToken]

== Execute the Published Document Actions  

To execute the published document actions, use the Submit Document to MuleSoft IDP action step in RPA. This action step enables you to browse through your published document actions and execute them by providing an Execution ID and the path to the file to process. Use the Execution ID when configuring the Retrieve Results from MuleSoft IDP action step to pull the results from the execution. 

The Submit Document to MuleSoft IDP action step executes document actions by impersonating a user in your organization. Therefore, you must use authentication credentials of a user that has the Execute Published Actions permission in Anypoint Platform.  

See xref:rpa-builder::toolbox-mulesoft-idp-submit-document-to-mulesoft-idp.adoc[] for configuration details. 

== Retrieve the Results of the Execution

To retrieve the results of a document action execution, use the Retrieve Results from MuleSoft IDP action step in RPA. This action step enables you to query the results of a document action execution by providing an Execution ID that you used before in the corresponding Submit Document to MuleSoft IDP execution.

See xref:rpa-builder::toolbox-mulesoft-idp-retrieve-results-from-mulesoft-idp.adoc[] for configuration details. 

== See Also 

* xref:creating-document-actions.adoc[]
* xref:publishing-document-actions.adoc[]
