= Getting Started with Document Processing

Before you analyze documents with IDP, you must create and publish document actions, the configurable schema definitions containing the necessary instructions to process your documents. 

After you publish a document action to Anypoint Exchange, you can programatically call the IDP API to execute the document action and extract data from a document. As a result, the document action analyzes the provided document and returns a response in JSON format with all the extracted fields. You can query the IDP API to check the status of an execution at any time.

== Document Actions 

include::partial$document-action.adoc[tag=definition]

IDP provides preconfigured *Invoice* and *Purchase Order* templates for creating custom document actions. Each template provides a set of expected fields to extract from the document into a structured response. When creating a new document action, choose the type that aligns best with the document to process. For example, the *Invoice* type can process invoices, receipts, and similar documents. If none of these types align with your documents, use the *Generic* type to fully customize the fields to extract by asking questions in natural language. 

After you create a document action, publish it to Anypoint Exchange to make it available for consumption from RPA and through the IDP API.

== Reviews

Document actions return a JSON response that contains the extracted fields and their detected values. Each of these values has a confidence score that determines the accuracy of the value during the extraction.

A document is queued for review if any of the following conditions is met: 

* At least one non-hidden field shows a confidence score lower than the configured threshold.
* At least one non-hidden field marked as required is missing or could not be extracted.

After a reviewer verifies and approves the result, the execution status changes to `SUCCEEDED`. For the possible statuses and their definitions, see the xref:automate-document-processing-with-the-idp-api.adoc#execution-status-reference[Execution Status Reference].

== IDP API 

You can trigger the execution of any of your published document actions to analyze the provided documents and query the results of the execution by using the IDP API. You must configure a connected app to call the IDP API. 

For configuration and usage instructions, see: xref:automate-document-processing-with-the-idp-api.adoc[].

== IDP and RPA Integration

You can execute your published document actions and query the results by using the Submit Document to MuleSoft IDP and Retrieve Results from MuleSoft IDP action steps from MuleSoft RPA. You must configure a connected app to call IDP and you must publish your document actions to make them available to RPA. 

For configuration and usage instructions, see: xref:automate-document-processing-with-rpa.adoc[].

== See Also

* xref:creating-document-actions.adoc[]
* xref:publishing-document-actions.adoc[]
* xref:reviewing-processed-documents.adoc[]
