= IDP Overview

MuleSoft Intelligent Document Processing (IDP) enables you to read invoices, purchase orders, and other unstructured or semi-structured documents and then analyze and refine the extracted content using AI capabilities to create a structured response.

With the simple IDP interface, you can create and publish document actions as APIs to use for further integration with RPA, Mule applications, and other systems, without subscribing to external services.

include::partial$document-action.adoc[tag=definition]

The confidence score represents the probability that IDP has properly extracted the value from a document. For example, a confidence score of 100% means that IDP extracted the value with total accuracy. However, a confidence score of 75% means that there's a 25% chance that the extracted value is not correct.

Each processed document shows a confidence score for each extracted field. When this value is lower than the defined threshold, IDP sends the document for review by a human to verify the accuracy of the extracted values. You can add single reviewers or teams to each document action. 

== Enhance Data Extraction With Einstein (Pilot)

When you add prompts to your document actions, you can select wether to use the default or Einstein's response. Einstein can answer complex questions that require further analysis of the document instead of just searching and extracting a field. For example, you can ask Einstein what's the total amount due in an invoice after deducting taxes and other values from the document. 

Use Einstein to analyze generic documents that don't use a standard format or are difficult to read without further analysis of the extracted data. 

== See Also 

* xref:document-processing.adoc[]
* xref:creating-document-actions.adoc[]
* xref:publishing-document-actions.adoc[]
* xref:rpa-home::index.adoc[]