= IDP Overview

Use IDP to extract data from documents and further analyze the content using AI capabilities. 

IDP incorporates third-party data extraction technologies such as AWS Textract, provides a simple interface so you don't need to log in or subscribe to external services, and enables you to create and publish document actions as APIs that you can use for further integration with RPA, Mule applications, and other systems. 

A document action is a multi-step process that scans a document using LLMs, filters out fields, and returns a structured response as a JSON object. Each document action defines the types of documents it expects as input and the fields to search for. You can configure Queries to enhance and refine the data extraction process. 

Each processed document shows a confidence score for each extracted field. When this value is lower than the defined threshold, the document is sent for review by a human to verify and confirm the accuracy of the extracted values. You can add single reviewers or teams to each document action. 

Use IDP to programmatically analyze invoices, purchase orders, and other documents and then consume the extracted values as a JSON response that you can use for further integration.

== See Also 

// Creating Document Actions
// Reviewing Processed Documents
// Automating Document Processing