= IDP Overview

MuleSoft Intelligent Document Processing (IDP) enables you to programmatically read invoices, purchase orders, and other documents and then analyze and refine the extracted content using AI capabilities to create a structured JSON response.

IDP incorporates third-party data extraction technologies such as AWS Textract, provides a simple interface so you don't need to log in or subscribe to external services, and enables you to create and publish document actions as APIs that you can use for further integration with Mule applications and other systems. 

include::partial$document-action.adoc[tag=definition]

Each processed document shows a confidence score for each extracted field. When this value is lower than the defined threshold, the document is sent for review by a human to verify and confirm the accuracy of the extracted values. You can add single reviewers or teams to each document action. 

== See Also 

* xref:creating-document-actions.adoc[]
* xref:publishing-document-actions.adoc[]
// Automating Document Processing