include::rpa-home::partial$automation-credits-2.adoc[tag=title]

include::rpa-home::partial$automation-credits-2.adoc[tag=intro]

include::rpa-home::partial$automation-credits-2.adoc[tag=conversionRates]

include::rpa-home::partial$automation-credits-2.adoc[tag=detailsAndSubscriptionPlans]

Analyzing documents with Einstein consumes Automation Credits and Einstein Requests. For more information about Einstein Requests, usage, and consumption, see https://www.salesforce.com/content/dam/web/en_us/www/documents/einstein-for-generative-ai-rate-card.pdf[Einstein Rate Card].

== Generative AI

The services contain features that use generative AI technology that may be provided by one or more third-parties as listed in the documentation applicable to the services. This documentation provides information and product requirements specific to these generative AI features and providers, including applicable third-party acceptable use policies which the customer must comply with when using the generative AI technology. Due to the nature of generative AI, the output that it generates may be unpredictable, and may include inaccurate or harmful responses. Before using any generative AI output, the customer is solely responsible for reviewing the output for accuracy, safety, and compliance with applicable laws and third-party acceptable use policies. The customer assumes all responsibility for output generated by the services and, as between Salesforce and the customer, such output is customer data.

include::idp::partial$einstein-model.adoc[]

[NOTE]
Einstein doesn't use customer data to train any models for document analysis in IDP.

== See Also 

* xref:ms-automation-credits-usage-types.adoc[]
