= Publishing Document Actions

You can build an automated pipeline for document processing by integrating your published document actions with RPA, Mule applications, and other systems. Publishing a document action makes it discoverable in RPA and available in Anypoint Exchange as an API that you can call.

== Document Action Versioning

You can use document action versioning to avoid breaking existing integrations when you modify a published document action. IDP follows semantic versioning but only increases the minor version number when you republish a document action. 

For example, when you publish a document action for the first time, IDP sets the version to `1.0.0`. If you modify this document action later and republish it, IDP sets the version number to `1.1.0`, and so on.

Consider this behavior when publishing document actions and ensure you call the desired version of the published document action in your integrations. 

== Before You Begin 

Ensure you have any of the following Anypoint permissions:

include::partial$permissions.adoc[tag=permissionManage]

include::partial$permissions.adoc[tag=permissionBuild]

== Publish a Document Action

To publish a document action: 

. Open the document in edit mode either by:
** Creating a new document action.
** Opening an existing document action in view mode and clicking *Open in Builder*.
. Click *Publish*.
. Verify the name and version of the asset and click *Publish*.
. Wait for the confirmation message and click *Close*.

== See Also

* xref:reviewing-processed-documents.adoc[]
* xref:creating-document-actions.adoc[]
* xref:automate-document-processing-with-the-idp-api.adoc[]
* xref:automate-document-processing-with-rpa.adoc[]
