= Quotas and Limits

The following table shows the quotas and limitations of the IDP service:  

[%header%autowidth.spread,cols=".^a,.^a]
|===
| Limit | Description
| Accepted File Formats 
a| PDF, PNG, JPG, TIFF (150 DPI or more recommended) +
The document action builder does not support previewing TIFF files. However, you can extract data and review results from these files.
| File Size Limits 
a| 
[%header%autowidth.spread,cols="a,a"]
!===
! Upload via UI 
! Upload via API
! 
* 10 files per upload
* 50 pages per file
* 8 MB per file
! 
* No limit on the number of files per upload
* 50 pages per file
* 10 MB per file
!===
| Prompt Limits 
a| 
* 30 per document action
* English prompts +
Prompts in other languages are not fully supported. 
* Unique prompts
+
Duplicate prompt names or instructions are not allowed.
| Prompt Response Limits 
a| 
* 128 characters for IDP NLP prompts.
| Document Languages 
a| 
Full English, Spanish, and German document support +
Analyzing documents in other languages is not fully supported. 
| Polling Limits 
a| 
10-second interval for retrieving results +
Applications must avoid polling for results more often than every 10 seconds. 
|===

== Document Retention Policy

IDP retains the document files and extracts data as needed to process the document extractions. IDP uses the following features to enhance data retention:

* Document Action Editor
+
IDP temporarily stores the files you modify in the editor during the testing process and immediately removes these files after you close the editor. IDP also removes the extracted data and the files when you end the session or upload a new file.
* Document Action Execution Endpoint
+
When you use the execution endpoint API, IDP stores the files in an S3 bucket and stores the data extracted during the execution securely. 

For all successful executions, IDP retains this data for seven days. For executions that require human review, IDP retains this data for seven days after the user task is completed. IDP retains any incomplete tasks for 60 days. Currently, you cannot configure these retention periods.

== Data Residency Policy:

IDP uses AWS services such as S3 and RDS to store files and the extracted data. IDP currently supports 2 regions: US (Virginia) and EU (Frankfurt, Germany). IDP stores the data closest to your Anypoint control plane region to ensure GDPR requirements. For example, if your Anypoint control plane runs in the EU region, IDP stores your data in the Frankfurt data center.