= Reviewing Processed Documents 

After processing a document, IDP queues it for review if:

* At least one field marked as _visible_ shows a confidence score lower than the configured threshold.
* At least one field marked as _visible_ and _required_ is missing or could not be extracted.

In this case, a user must review the document to verify the values for the conflicting fields. After the review is finished, the status of the extraction changes to `SUCCEEDED`.

== Before You Begin 

Before you can review a document, ensure that: 

* You are assigned as a reviewer in the corresponding document action.

== Review a Document in the UI

To review the results of a processed document:

. In the navigation panel, click *Review Tasks*.
. Click the name of the document to review.
. In the *Results* panel, verify the values extracted from each field.
+
During this step, you can modify the values that require adjustment.
. After reviewing all values, click *Submit This Page*.
+
If there are more than one results page, click *Submit and Next* and continue the process until you review all pages.

== See Also

* xref:adding-reviewers.adoc[]