= Reviewing Processed Documents 

After processing a document, IDP queues it for review if:

* At least one of the extracted values shows a confidence score lower than the threshold defined in the document action for that field.
* A field mark as required is not detected in the document. 

In this case, a user must review the document to verify the values for the conflicting fields. After the review is finished, the extraction result is available for consumption.

== Before You Begin 

Before you can review a document, ensure that: 

* You are assigned as a reviewer in the corresponding document action.

== Review a Document in the UI

To review the results of a processed document:

. In the navigation panel, click *Review Tasks*.
. Select the document to review by clicking its name.
. Navigate the *Results* panel and verify the values extracted from each field.
+
During this step, you can modify the values that require adjustment.
. After reviewing all values, click *Submit This Page*.
+
If there are more than one results page, click *Submit and Next* and continue the process until you review all values.

== See Also

* xref:assigning-reviewers.adoc[]