// tag::createConnectedApp[]
== Create a Connected App

To communicate with the IDP API, create a connected app with the following details: 

* Type: `App acts on its own behalf (client credentials)`
* Scopes: `Execute Published Actions`

After you create the connected app, copy its *ID* and *Secret* for further use when you obtain the access token. 

For more information, see xref:access-management::connected-apps-overview.adoc[].

// end::createConnectedApp[]

// tag::obtainAccessToken[]
== Obtain the Access Token

After you configure the connected app, use the following `curl` command to get the token: 

[source,bash,linenums]
----
curl --location --request POST 'https://anypoint.mulesoft.com/accounts/api/v2/oauth2/token' \ // <1>
--header 'Content-Type: application/json' \
--data-raw '{
 "grant_type": "client_credentials",
 "client_id": "<connected-app-client-id>", // <2>
 "client_secret": "<connected-app-client-secret>" // <3> 
}'
----
[calloutlist]
.. If you are in the EU region, use the `eu1.anypoint.mulesoft.com` domain.
.. Replace `<connected-app-client-id>` with the client ID from your connected app.
.. Replace `<connected-app-client-secret>` with the client secret from your connected app.

Use the access token when calling the IDP API.

// end::obtainAccessToken[]
